# Generated by Django 5.1.4 on 2024-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_tag_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='helper_text',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
